/*
 * This is generated by the getStubs.tcl tool (see the tcl distribution)
 * out of the rbc.decls file 
 */

#include "rbc.h"

/* !BEGIN!: Do not edit below this line. */

const RbcStubs rbcStubs = {
    TCL_STUB_MAGIC,
    0,
    Rbc_CreateVector, /* 0 */
    Rbc_GetVector, /* 1 */
    Rbc_ResizeVector, /* 2 */
    Rbc_NameOfVector, /* 3 */
    Rbc_ResetVector, /* 4 */
    Rbc_VectorData, /* 5 */
    Rbc_VectorLength, /* 6 */
    Rbc_VectorSize, /* 7 */
    Rbc_VectorDirty, /* 8 */
    Rbc_VectorExists2, /* 9 */
    Rbc_FreeVector, /* 10 */
};

/* !END!: Do not edit above this line. */
